//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportCenterManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class admins
    {
        public admins()
        {
            this.events = new HashSet<events>();
            this.price_lists = new HashSet<price_lists>();
            this.reservations = new HashSet<reservations>();
        }
    
        public int ID { get; set; }
        public int EMPLOYEE_ID { get; set; }
    
        public virtual employees employees { get; set; }
        public virtual ICollection<events> events { get; set; }
        public virtual ICollection<price_lists> price_lists { get; set; }
        public virtual ICollection<reservations> reservations { get; set; }
    }
}
