//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportCenterManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class clients
    {
        public clients()
        {
            this.sales = new HashSet<sales>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public string PIN { get; set; }
        public string SEX { get; set; }
        public Nullable<int> ACCOUNT_ID { get; set; }
    
        public virtual accounts accounts { get; set; }
        public virtual ICollection<sales> sales { get; set; }
    }
}
