//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportCenterManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class coaches
    {
        public coaches()
        {
            this.trainings = new HashSet<trainings>();
        }
    
        public int ID { get; set; }
        public int EMPLOYEE_ID { get; set; }
    
        public virtual employees employees { get; set; }
        public virtual ICollection<trainings> trainings { get; set; }
    }
}
