//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportCenterManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class dates
    {
        public dates()
        {
            this.reservation_dates = new HashSet<reservation_dates>();
        }
    
        public int ID { get; set; }
        public System.DateTime DATE { get; set; }
    
        public virtual ICollection<reservation_dates> reservation_dates { get; set; }
    }
}
