//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportCenterManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class events
    {
        public events()
        {
            this.reservations = new HashSet<reservations>();
            this.tickets = new HashSet<tickets>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public int CREATOR_ID { get; set; }
    
        public virtual admins admins { get; set; }
        public virtual ICollection<reservations> reservations { get; set; }
        public virtual ICollection<tickets> tickets { get; set; }
    }
}
