//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportCenterManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class facilities
    {
        public facilities()
        {
            this.facilities1 = new HashSet<facilities>();
            this.reservations = new HashSet<reservations>();
        }
    
        public int ID { get; set; }
        public long CAPACITY { get; set; }
        public string NAME { get; set; }
        public Nullable<bool> RESERVABLE { get; set; }
        public Nullable<int> PARENT_FACILITY { get; set; }
    
        public virtual ICollection<facilities> facilities1 { get; set; }
        public virtual facilities facilities2 { get; set; }
        public virtual ICollection<reservations> reservations { get; set; }
    }
}
