//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportCenterManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class price_lists
    {
        public price_lists()
        {
            this.sales = new HashSet<sales>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string PRICE_ALGORITHM { get; set; }
        public int CREATOR_ID { get; set; }
    
        public virtual admins admins { get; set; }
        public virtual ICollection<sales> sales { get; set; }
    }
}
