//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportCenterManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation_dates
    {
        public int RESERVATION_ID { get; set; }
        public Nullable<int> DATE_ID { get; set; }
    
        public virtual dates dates { get; set; }
        public virtual reservations reservations { get; set; }
    }
}
