//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportCenterManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales
    {
        public sales()
        {
            this.services = new HashSet<services>();
        }
    
        public int ID { get; set; }
        public System.DateTime DATE { get; set; }
        public Nullable<int> CLIENT_ID { get; set; }
        public Nullable<int> CASHIER_ID { get; set; }
        public int PRICE_LIST_ID { get; set; }
    
        public virtual cashiers cashiers { get; set; }
        public virtual clients clients { get; set; }
        public virtual price_lists price_lists { get; set; }
        public virtual ICollection<services> services { get; set; }
    }
}
