//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportCenterManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class services
    {
        public services()
        {
            this.subscriptions = new HashSet<subscriptions>();
            this.tickets = new HashSet<tickets>();
            this.sales = new HashSet<sales>();
        }
    
        public int ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> FACILITIES_ID { get; set; }
        public Nullable<int> TRAINING_ID { get; set; }
    
        public virtual trainings trainings { get; set; }
        public virtual ICollection<subscriptions> subscriptions { get; set; }
        public virtual ICollection<tickets> tickets { get; set; }
        public virtual ICollection<sales> sales { get; set; }
    }
}
