//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportCenterManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class tickets
    {
        public int ID { get; set; }
        public int SERVICE_ID { get; set; }
        public Nullable<int> EVENT_ID { get; set; }
    
        public virtual events events { get; set; }
        public virtual services services { get; set; }
    }
}
